postgres:
    host: localhost
    database: cantonres
    user: kevin
    password: foobar
    joininfo_table: CREATE TABLE joininfo (id SERIAL PRIMARY KEY,
        ingress_id VARCHAR(35) NOT NULL,
        telegram_id BIGINT NOT NULL,
        telegram_username VARCHAR(35) NOT NULL,
        area VARCHAR(25) NOT NULL,
        other VARCHAR(50),
        created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)
    admininfo_table:
        CREATE TABLE admininfo (id SERIAL PRIMARY KEY,
        telegram_id BIGINT NOT NULL,
        area VARCHAR(2) NOT NULL,
        created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)
bot:
    token: 265836060:AAFUAYbxHfYgVbrOx8R3bOJMxPPBM-2IO_M
